Numpy is mainly used to handle homogeneous multi dimensional array, usually numbers. 

In [2]:
import numpy as np

In [12]:
a = np.array([[1, 2, 3], [1, 2, 3]])
type(a)

numpy.ndarray

In [ ]:
a.ndim # dimensions

2

In [ ]:
a.shape 

(2, 3)

In [ ]:
a.size # total number of elements

6

In [ ]:
a.dtype # element data typpe

dtype('int32')

In [18]:
np.arange(1,10, 2) # similar to pythons range

array([1, 3, 5, 7, 9])

In [19]:
np.zeros((4, 5)) # a 4x5 matrix with all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones((4, 5)) # a 4x5 matrix with all ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.empty(a.shape) # random values 

array([[3.47739925e-081, 5.78365929e+174, 9.84802495e-072],
       [2.63222976e-052, 5.55505059e+170, 7.56571287e-307]])

In [24]:
np.arange(12).reshape(3, 4) # reshape 1x12 ndarray to 3x4 ndarray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
np.linspace(0, 10, 20) # same as matplot linspace (start, end, number of equidistant values between start and end

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
np.eye(5) # a 5x5 identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.random.rand(3, 3) # 3x3 matrix with elements uniformly distributed from [0, 1)

array([[0.56684707, 0.12075848, 0.5036569 ],
       [0.48521875, 0.78270592, 0.43110091],
       [0.41911459, 0.56769125, 0.30052818]])

In [29]:
np.random.randn(3, 3) # 3x3 matrix with elements sampled from a gaussian distribution with mean 0, variance 1

array([[-0.65095925,  1.26685049, -1.8489056 ],
       [ 1.16080036, -0.75523526,  0.22815743],
       [-0.13907007,  0.0911434 ,  1.10320968]])

In [31]:
np.random.randint(1, 10, 10) # 10 random integers from 1 to 10

array([3, 5, 5, 3, 8, 2, 1, 5, 9, 9])

In [34]:
x = np.arange(10) 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
x.min()

0

In [35]:
x.max()

9

In [36]:
x.argmin()

0

In [37]:
x.argmax()

9

Indexing is an important feature of numpy

In [58]:
x = np.arange(11)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
x[8]

8

In [60]:
x[1:5]

array([1, 2, 3, 4])

In [61]:
x[-1]

10

In [63]:
slice_x = x[0:5]
slice_x[:]= 5
slice_x

array([5, 5, 5, 5, 5])

In [ ]:
x # assignment doesn't make a new copy in numpy; so make a copy using copy method

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [65]:
slice_x_copy = x[5:].copy()
slice_x_copy[:] = 10
slice_x_copy

array([10, 10, 10, 10, 10, 10])

In [67]:
x # last 5 elements didnot change

array([ 5,  5,  5,  5,  5,  5,  6,  7,  8,  9, 10])

In [69]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [70]:
m[2] # returns second row

array([ 8,  9, 10, 11])

In [71]:
m[2][1] # (2, 1) element

9

In [72]:
m[2, 1] # (2, 1) element

9

In [74]:
m[2:, :2] # everything from third row (zero indexing) and everything before second column

array([[ 8,  9],
       [12, 13]])

In [76]:
m > 10 # matrix with boolean values, each element corresponds to truth of m[i][j] > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True]])

In [78]:
m[m>10] # only return elements in m that are greater than m , its a 1d vector

array([11, 12, 13, 14, 15])

Numpy operations

In [79]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [82]:
a+a # element wise sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
a - a # element wise difference

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [86]:
a.reshape(2, 5) * a.reshape(2, 5) # element wise product

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [88]:
a + 100 # add 100 to every element

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [89]:
a ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [90]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [91]:
np.exp(a)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [92]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])